[package]
name = "ipfs-api"
version = "0.0.1"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
rocket_okapi = { version = "0.8.0-rc.2", features = ["swagger", "rapidoc"] }
serde = "1.0"
ipfs-api-backend-hyper = { version = "0.5", features = ["with-send-sync"] }
rand = "0.8.5"